<a href="https://colab.research.google.com/github/McKendreevv/Mis433/blob/main/MVV_python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [1]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? McKendree
Welcome, McKendree!


In [2]:
# complete your program here
f = input('Please enter the temperature in Fahrenheit: ')

print(f)

f=float(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 140
140
140.0F is 60.0 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [3]:
# complete your program here
c = input('Please enter the temperature in Celcius: ')

print(c)

c=float(c)

#Celsius = (Fahrenheit – 32)*5/9
f = (9/5*c) + 32

print(f'{c}C is {f} in Fahrenheit. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Celcius: 60
60
60.0C is 140.0 in Fahrenheit. 


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [6]:
# complete your program here
d = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? (type C or F)')

if m == 'C':
  d=float(d)
  f = (9/5*d) + 32
  print(f'{d}C is {f} in Fahrenheit')
elif m == 'F':
  d=float(d)
  c = (d - 32) * 5/9
  print(f'{d}F is {c} in Celsius')
else:
  print('Invalid input')


Please enter the temperature: 60
Is this in Celsius or Fahrenheit? (type C or F)C
60.0C is 140.0 in Fahrenheit


## Question 2

Have some fun with strings.

In [ ]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [8]:
# Find the length of this sentence.
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

print (len(sentence))
#prints the number of charecters in the sentance string

48


In [9]:
# Convert the whole string to lower case.
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

print (sentence.lower())
#prints the sentance string converted to lowercase

talk is cheap. show me the code - linus torvalds


In [10]:
# Extract a substring from the 10th character from left to the 10th character from right.
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

print (sentence[9:-9])
#prints the 10th character from left to the 10th character from right

heap. Show me the code - Linus


In [11]:
# Split the sentence into a list of substrings by space ' '.
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

print(sentence.split())
#splits the sentance into a list of substrings by

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [19]:
# Given the sentence, output a list of words in lowercase (without punctuations).
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

print(sentence.lower().replace('.','').replace('-','').split())

['talk', 'is', 'cheap', 'show', 'me', 'the', 'code', 'linus', 'torvalds']


In [16]:
# Count the total number of vowels in the sentence.
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

vowels = 'aeiou'
count = sum(1 for char in sentence if char in vowels)
# adds up the charecters in the sentance as long as the charecters are listed in vowels and then stores the sum in a variable 'count'
print(count)




13


In [17]:
# Find the positions (indexes) of all vowels in the sentence.
for i in range(len(sentence)):
    if sentence[i] in vowels:
        print(i)
    ...

1
5
10
11
17
21
25
28
30
35
37
41
44


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [20]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for i in range(5):
  cubes.append(i**3)
print(cubes)


[0, 1, 8, 27, 64]


In [21]:
# Use list comprehension to create the same list
cubes = [i**3 for i in range(5)]
print(cubes)

[0, 1, 8, 27, 64]


In [22]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"

vowels = 'aeiou'
vowels_index = [i for i in range(len(sentence)) if sentence[i] in vowels]
print(vowels_index)

[1, 3, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47]


In [ ]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = int(input('How many numbers do you want? '))

# add your code here
if n == 1:
  fibonacci= [0]
elif n == 2:
  fibonacci= [0,1]
elif n > 2:
  fibonacci = [0,1]
  while len(fibonacci) < n:
    fibonacci.append(fibonacci[-1] + fibonacci[-2])

print(fibonacci)

How many numbers do you want? 10
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [23]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {}

v_dict['Pfizer'] = 0.95
v_dict['Moderna'] = 0.95
v_dict['AstraZeneca'] = 0.72
v_dict['Johnson & Johnson'] = 0.66

In [25]:
v = input('Which vaccine? Enter Name: ')
# print the efficacy of the vaccine

print(v_dict[v])

Which vaccine? Enter Name: Moderna
0.95


In [26]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary

v_dict['Sputnik V'] = 0.914


In [27]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary

v_dict['Sinovac'] = 0.5038


In [28]:
# Print vaccines with efficacy lower than 90%.

for v in v_dict:
  if v_dict[v] < 0.9:
    print(v)

AstraZeneca
Johnson & Johnson
Sinovac


In [29]:
# delete the Sinovac vaccine from the dictionary.

del v_dict['Sinovac']

In [31]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}

# Use a loop to iterate all characters
# add your code here
for ch in sentence:
    if ch.isalpha():
        ch_dict[ch] = ch_dict.get(ch, 0) + 1

# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [32]:
import numpy as np

In [39]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
arr = np.array([2 * i for i in range(1, 21)])
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [40]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
arr = np.array([2 * i - 1 for i in range(1, 21)])
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [38]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
arr = np.array([[i + 10 * j for i in range(10)] for j in range(10)])
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [42]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0, 1, (10, 10))
print(M)


[[ 0.44894859  0.40446836 -0.03349833 -0.36671185  1.74977677 -0.10831745
  -0.71701801 -0.07254857 -0.90848055  0.87333562]
 [ 0.97414254  0.12151003 -1.61540197 -0.58132867 -2.56157513 -1.76298458
  -0.23693939 -0.03622363 -0.54473994 -0.4068408 ]
 [-1.67625308  1.54140703 -0.84234585 -1.44324968 -1.00639907 -0.40992715
  -0.70449337  0.71916492  0.01539794  0.2842745 ]
 [ 1.16457839 -1.64828552  0.37834256 -1.42453265  1.35142179  0.53946964
  -0.81278453  0.40226571 -1.15947503 -0.78556308]
 [-0.0546223  -1.32261372 -2.23655516  0.77070735 -1.13554591 -0.94396811
   0.26335253 -0.40080861 -0.14165316 -0.51586392]
 [ 0.36571869  2.02861138  0.78900773 -0.460812    0.03566946  0.19363013
   1.05328139 -0.60290312  0.1066919   0.78655757]
 [ 0.80488622  0.65058772  0.70740857  1.28704404  1.25819274  1.69563333
  -0.61438606 -0.86655699 -1.33912703  0.0461792 ]
 [-0.00536861 -2.01082819  0.80238457  0.86731725 -0.86347762  0.15504802
   1.35664544 -1.44923665 -1.40793428  1.7726912 ]


In [43]:
# Count the numbers in M with an absolute value greater than 1.
count = np.sum(np.abs(M) > 1)
print(count)

37


In [44]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = input('Row count: ')

# Input the number of rows (input another integer >= 3)
c = input('column count: ')

# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, (int(r), int(c)))
print(arr)

Row count: 10
column count: 10
[[10 18 12 15 14 17 11 14 17 19]
 [11 13 10 12 10 10 11 19 14 12]
 [17 19 12 16 13 15 12 13 11 19]
 [17 19 12 14 16 16 14 12 10 18]
 [12 12 15 14 15 18 13 18 13 12]
 [13 17 18 10 14 15 12 18 17 12]
 [14 19 10 14 17 11 15 12 13 11]
 [10 13 10 13 10 10 19 18 17 19]
 [11 12 14 12 15 15 17 10 17 13]
 [16 19 18 10 18 18 17 11 11 13]]


In [45]:
# output the element in the first row and the third column
print(arr[0, 2])

12


In [46]:
# output the element in the second row and the last column
print(arr[1, -1])

12


In [47]:
# output the second row of the array
print(arr[1, :])


[11 13 10 12 10 10 11 19 14 12]


In [48]:
# output the second last row of the array
print(arr[-2, :])


[11 12 14 12 15 15 17 10 17 13]


In [49]:
# output the second column of the array
print(arr[:, 1])

[18 13 19 19 12 17 19 13 12 19]


In [50]:
# output the second last column of the array
print(arr[:, -2])

[17 14 11 10 13 17 13 17 17 11]


In [51]:
# output the upper-left 3x3 sub-array
print(arr[:3, :3])

[[10 18 12]
 [11 13 10]
 [17 19 12]]


In [52]:
# output the bottom-left 3x3 sub-array
print(arr[-3:, :3])

[[10 13 10]
 [11 12 14]
 [16 19 18]]


In [53]:
# output the upper-right 3x3 sub-array
print(arr[:3, -3:])

[[14 17 19]
 [19 14 12]
 [13 11 19]]


In [54]:
# output the bottom-right 3x3 sub-array
print(arr[-3:, -3:])

[[18 17 19]
 [10 17 13]
 [11 11 13]]


In [61]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.array([i for i in range(1, 51)]).reshape(5,10)
# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]
print(A)


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [66]:
# add a row [51,...,60] to A

new_row = np.array([[51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])
A = np.append(A, new_row, axis=0)
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [67]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1, A2 = np.split(A, 2)

print(A1)
print(A2)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [68]:
# Add 10 to each element of A
A = A + 10
print(A)

[[11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]]


In [69]:
# Calculate the square root of each element in A
A = np.sqrt(A)
print(A)

[[3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
  4.12310563 4.24264069 4.35889894 4.47213595]
 [4.58257569 4.69041576 4.79583152 4.89897949 5.         5.09901951
  5.19615242 5.29150262 5.38516481 5.47722558]
 [5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
  6.08276253 6.164414   6.244998   6.32455532]
 [6.40312424 6.4807407  6.55743852 6.63324958 6.70820393 6.78232998
  6.8556546  6.92820323 7.         7.07106781]
 [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
  7.54983444 7.61577311 7.68114575 7.74596669]
 [7.81024968 7.87400787 7.93725393 8.         8.06225775 8.1240384
  8.18535277 8.24621125 8.30662386 8.36660027]]


In [70]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape
print (M)

[[ 0.44894859  0.40446836 -0.03349833 -0.36671185  1.74977677 -0.10831745
  -0.71701801 -0.07254857 -0.90848055  0.87333562]
 [ 0.97414254  0.12151003 -1.61540197 -0.58132867 -2.56157513 -1.76298458
  -0.23693939 -0.03622363 -0.54473994 -0.4068408 ]
 [-1.67625308  1.54140703 -0.84234585 -1.44324968 -1.00639907 -0.40992715
  -0.70449337  0.71916492  0.01539794  0.2842745 ]
 [ 1.16457839 -1.64828552  0.37834256 -1.42453265  1.35142179  0.53946964
  -0.81278453  0.40226571 -1.15947503 -0.78556308]
 [-0.0546223  -1.32261372 -2.23655516  0.77070735 -1.13554591 -0.94396811
   0.26335253 -0.40080861 -0.14165316 -0.51586392]
 [ 0.36571869  2.02861138  0.78900773 -0.460812    0.03566946  0.19363013
   1.05328139 -0.60290312  0.1066919   0.78655757]
 [ 0.80488622  0.65058772  0.70740857  1.28704404  1.25819274  1.69563333
  -0.61438606 -0.86655699 -1.33912703  0.0461792 ]
 [-0.00536861 -2.01082819  0.80238457  0.86731725 -0.86347762  0.15504802
   1.35664544 -1.44923665 -1.40793428  1.7726912 ]


In [71]:
# Print the mean, standard devietion of all numbers in M
print(np.mean(M))
print(np.std(M))

-0.0974784179560965
1.0620945291164232


In [72]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M

print(np.max(M))          # maximum
print(np.percentile(M, 75))  # 3rd quartile (Q3)
print(np.median(M))       # median
print(np.percentile(M, 25))  # 1st quartile (Q1)
print(np.min(M))          # minimum

2.0286113823746446
0.7854285090592772
-0.06358543668466424
-0.847628791390941
-2.6949427703108575
